apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-storage
  namespace: catalystlab-shared
  labels:
    app: tempo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
